### ISSUE TITLE
Needs a stop mechanism

### ISSUE THREAD

**Issue by cscuderi** [tylergaw/css-shaky-animation#1]
This effect seems to be in contrast with an "A" level requirement of WCAG 2.0: http://www.w3.org/WAI/WCAG20/quickref/#qr-time-limits-pause

**Comment by tylergaw** [comment]
@cscuderi Do you think the pause/play should pause the whole title sequence or just stop the "shaking".

Also, probably won't put it in since this is just a one-off demo to show the technique, not really meant for practical use.

**Comment by cscuderi** [comment]
@tylergaw I think it should just stop the shaking.

I figured it's not something super important... But as of Jan. 1 2014, where I live, I could be penalized or fined for building a new website that does not comply to WCAG level A.

Anyways, neat effect, cool implementation. It reminds me of some old school cartoons... pretty nostalgic.

**Comment by tylergaw** [comment]
@cscuderi Ah, I see. The WCAG guidelines are a bit tough to decipher. I wonder if the shaking would fall under http://www.w3.org/WAI/WCAG20/quickref/#seizure ?

Either way, stopping animations like this is fairly easy. Just a matter of adding or removing a class that has the animation applied to it.

**Comment by cscuderi** [comment]
@tylergaw Yeah, they are pretty verbose and unclear sometimes. Some things are just hard to put into words.

I'm not sure it fits under seizures because it doesn't seem to "flash" (W3C definition: http://www.w3.org/TR/2008/REC-WCAG20-20081211/#flash-def).
